BPS.Intake.Web/Areas/TrainingTeam/Controllers/CommonSearchFilterController.cs
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Threading.Tasks;
using BPS.Intake.Infrastructure.Types;
using BPS.Intake.Domain.Service;
using BPS.Intake.Web.Areas.TrainingTeam.Models.CommonSearch;
using System;


namespace BPS.Intake.Web.Areas.TrainingTeam.Controllers
{
    public class CommonSearchFilterController : Controller
    {
        private readonly IQuestionGroupService _groupService;
        private readonly IQuestionCategoryService _categoryService;

        public CommonSearchFilterController(IQuestionGroupService groupService, IQuestionCategoryService categoryService)
        {
            _groupService = groupService;
            _categoryService = categoryService;
        }

        private List<SelectListItem> GetSelectList(IEnumerable item, string dataValueField = "Id", string dataTextField = "Name")
        {
            List<SelectListItem> items = new SelectList(item, dataValueField, dataTextField).ToList();
            items.Insert(0, (new SelectListItem { Text = "-- Select an item --", Value = "" }));
            return items;
        }
        private List<SelectListItem> GetSelectList(IEnumerable item,object selectedValue, string dataValueField = "Id", string dataTextField = "Name")
        {
            List<SelectListItem> items = new SelectList(item, dataValueField, dataTextField, selectedValue).ToList();
            items.Insert(0, (new SelectListItem { Text = "-- Select an item --", Value = "" }));
            return items;
        }

        //public async Task<PartialViewResult> ControlSearchCategory(CategoryType categoryType)
        //{
        //    var categoryDtoList = await _categoryService.GetByType(categoryType);
        //    return PartialView("~/Areas/TrainingTeam/Views/CommonSearchFilter/_ControlSearchDropDownList.cshtml",
        //        new DropDownViewModel() { SelectList = GetSelectList(categoryDtoList), Name = "CategorySelect" });
        //}

        //public async Task<PartialViewResult> ControlSearchGroup(GroupType groupType)
        //{
        //    var groupDtoList = await _groupService.GetGroupByType(groupType);
        //    return PartialView("~/Areas/TrainingTeam/Views/CommonSearchFilter/_ControlSearchDropDownList.cshtml",
        //        new DropDownViewModel() { SelectList = GetSelectList(groupDtoList), Name = "GroupSelect" });
        //}

        public PartialViewResult ControlSearchType(SRPQuestionCategory questionType)
        {
            var dictionary = new Dictionary<int, string>();
            var enumerationType = typeof(SRPQuestionCategory);
            foreach (int value in Enum.GetValues(enumerationType))
            {
                var name = Enum.GetName(enumerationType, value);
                dictionary.Add(value, name);
            }
            return PartialView("~/Areas/TrainingTeam/Views/CommonSearchFilter/_ControlSearchDropDownList.cshtml",
                new DropDownViewModel() { SelectList = GetSelectList(dictionary, (int)questionType, "Key", "Value"), Name = "TypeSelect"});
        }

    }

}

BPS.Intake.Web/Areas/TrainingTeam/Views/CommonSearchFilter/_ControlSearch.cshtml
@using BPS.Intake.Infrastructure.Types
@model BPS.Intake.Web.Areas.TrainingTeam.Models.CommonSearch.CommonSearchViewModel
<input type="hidden" id="formId" value="@Model.GroupType" />
<fieldset class="fsStyle">
    <legend class="legendStyle">
        <span class="glyphicon glyphicon-search"></span> Search
    </legend>
    <div id="commonSearchControl">
        <div class="form-horizontal wrapper-center clearfix">
            <div class="form-group col-md-6">
                <div class="form-group">
                    <label class="col-md-4 control-label">
                        Category
                    </label>
                    <div class="col-md-8" id="divCategory">
                        @Html.Action("ControlSearchCategory", "CommonSearchFilter", new { categoryType = Model.CategoryType })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-4 control-label">
                        Group
                    </label>
                    <div class="col-md-8" id="divGroup">
                        @Html.Action("ControlSearchGroup", "CommonSearchFilter", new { groupType = Model.GroupType })
                    </div>
                </div>
            </div>
            @if (Model.CategoryType == (int)CategoryType.Question)
            {
                <div class="form-group col-md-6">
                    <div class="form-group">
                        <label class="col-md-4 control-label">
                            Type
                        </label>
                        <div class="col-md-8" id="divType">
                            <div id="categoryWraper">
                                <select class="form-control formindiactor elementAction" id="select_dropdown" name="TypeSelect">
                                    <option selected="selected" value="1">Multiple Choice</option>
                                    <option value="2">Essay</option>
                                </select>
                            </div>
                             @*@Html.Action("ControlSearchType", "CommonSearchFilter", new { questionType = Model.Type })*@
                        </div>
                    </div>
                </div>
            }           

            <div class="form-group col-md-6">
                <div class="form-group">
                    <label class="col-md-4 control-label">
                        Name
                    </label>
                    <div class="col-md-8">
                        <input type="text" class="form-control col-md-4" id="searchName" name="searchName" placeholder="Enter a name" onkeypress="if(event.keyCode===13)Search();" />
                    </div>
                </div>
            </div>

            <div class="form-group col-md-6">
            </div>
            <div class="form-group col-md-6">
                <div class="set-btns text-center pull-right">
                    <input type="hidden" id="urlCallback" value="@Model.CallBack" />
                    <button id="Search" class="btn btn-default btn-1e" onclick="Search()"><span class="glyphicon glyphicon-search"></span> Search</button>
                    <button id="Reset" class="btn btn-warning" onclick="Reset()"><span class="glyphicon glyphicon-refresh"></span> Reset</button>
                </div>
            </div>
        </div>

    </div>
</fieldset>

@Scripts.RenderFormat("<script type=\"text/javascript\" src=\"{0}\"></script>", "~/bundles/CommonSearch")

BPS.Intake.Web/Areas/TrainingTeam/Views/CommonSearchFilter/_ControlSearchDropDownList.cshtml
@model BPS.Intake.Web.Areas.TrainingTeam.Models.CommonSearch.DropDownViewModel
    <div id="categoryWraper">
        @Html.DropDownList(Model.Name, Model.SelectList, 
                 new
                 {
                     @id = "select_dropdown",
                     @class = "form-control formindiactor elementAction"
                 })
    </div>